version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/.github'
    schedule:
      interval: 'weekly'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
