# Requires a repo & package write access GitHub PAT encrypted to `GH_TOKEN`
env:
  GH_TOKEN: ENCRYPTED[a83a3d33c85c1d0439cbfdb99f81551f87b7bfc3de072a36822d8019ef5f7d5a4aa6c7f47c975db2afa3a3c60f24384d]
  NO_PUSH: "true"

jupyter_book_task:
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  auto_cancellation: true
  env:
    JOBS: 1
    TIMEOUT: 600
  container:
    dockerfile: cirrus.Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  notebook_script: >
    find docs/ -name '*.ipynb' |
    parallel -j${JOBS} --joblog /tmp/log
    jupyter nbconvert --to notebook
    --ExecutePreprocessor.timeout=${TIMEOUT}
    --ExecutePreprocessor.kernel_name="julia-$(julia -e 'print(VERSION.major, ".", VERSION.minor)')"
    --execute --inplace
  stats_script: cat /tmp/log
  build_script: jupyter-book build docs/ --keep-going
  pages_script: |
    if [[ ${CIRRUS_BRANCH} == 'main' && ${NO_PUSH} != 'true' ]]; then
      echo "Deploying to GitHub pages..."
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -nofp docs/_build/html
    fi
