name: Build Binder Container

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  pull-requests: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Remove binder folder if present
      run: rm -rf .binder/ || true
    - name: Build binder image with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: ghcr.io
        DOCKER_USERNAME: ${{ github.repository_owner }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        LATEST_TAG_OFF: true
        ADDITIONAL_TAG: binder
        PUBLIC_REGISTRY_CHECK: true
    - name: Add back binder folder and Dockerfile
      run: |
        mkdir -p .binder
        echo "FROM ${{ env.IMAGE_NAME }}:binder" >> .binder/Dockerfile
    - name: Create Pull Request if binder Dockerfile has changed
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        title: Binder Dockerfile
        add-paths: .binder/Dockerfile
        branch: binder-dockerfile
