name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/linkcheck.yml'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.3-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python dependencies
        run: pip install --no-cache-dir -r .github/requirements.txt
      - name: Check links
        run: jupyter-book build docs/ --builder linkcheck
