name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

env:
  JULIA_PKG_PRECOMPILE_AUTO: '0'
  JULIA_NUM_THREADS: 'auto'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Setup Julia Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .ci/Dockerfile
          tags: julia:test
          load: true
          target: base
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
      - name: Update Julia dependencies
        run: >
          docker run --rm
          --workdir="/work"
          -v ${{ github.workspace }}:/work
          -e JULIA_PKG_PRECOMPILE_AUTO
          -e JULIA_NUM_THREADS
          julia:test
          --color=yes --project=@. -e "import Pkg; Pkg.instantiate()"
      # Authenticate using a custom GitHub APP
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Julia Dependency Update
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            automerge
