name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Load Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .ci/Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
      - name: Update Julia dependencies
        run: docker run -v ${{ github.workspace }}:/work -e JULIA_PKG_PRECOMPILE_AUTO=0 {{ env.IMAGE_NAME }}:test julia --color=yes --project=/work --threads=auto -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Package Update
          token: ${{ secrets.PAT }} # PAT with repo access
          labels: |
            automerge
